//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hogwarts.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HogwartsEntities : DbContext
    {
        public HogwartsEntities()
            : base("name=HogwartsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Houses> Houses { get; set; }
        public virtual DbSet<HouseScores> HouseScores { get; set; }
        public virtual DbSet<Quidditch> Quidditch { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<StudentsProfile> StudentsProfile { get; set; }
        public virtual DbSet<Subjects> Subjects { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
        public virtual DbSet<Timetable> Timetable { get; set; }
    }
}
