//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hogwarts.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseScores
    {
        public int Id { get; set; }
        public int HouseId { get; set; }
        public int ScoreValue { get; set; }
        public int ScoreYear { get; set; }
    
        public virtual Houses Houses { get; set; }
    }
}
