//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hogwarts.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quidditch
    {
        public int Id { get; set; }
        public int WinnerHouseId { get; set; }
        public int SecondHouseId { get; set; }
        public int WinnerScore { get; set; }
        public int SecondScore { get; set; }
        public System.DateTime GameDate { get; set; }
    
        public virtual Houses Houses { get; set; }
        public virtual Houses Houses1 { get; set; }
    }
}
