//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hogwarts.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsProfile
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
